# Generated by Django 3.2.4 on 2021-08-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0021_auto_20210714_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='state',
            field=models.SmallIntegerField(choices=[(1, 'Unflagged'), (2, 'Flagged'), (3, 'Flag rejected by the moderator'), (4, 'Comment modified by the author')], default=1),
        ),
    ]
